[build]
builder = "nixpacks"

[deploy]
preDeployCommand = "psql $DATABASE_URL -f server/db/gohome_schema.sql"
startCommand = "uvicorn server.gohome_app:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
